// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using videogame_randomized_back.Data;

#nullable disable

namespace videogame_randomized_back.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309224025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("videogame_randomized_back.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "background_image");

                    b.Property<string>("DescriptionRaw")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description_raw");

                    b.Property<int?>("Metacritic")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "metacritic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "note");

                    b.Property<int?>("PersonalRating")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "personalRating");

                    b.Property<double>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<string>("Released")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "released");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "savedAt");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SavedAt");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("videogame_randomized_back.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("videogame_randomized_back.Models.GamePlatform", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("videogame_randomized_back.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("videogame_randomized_back.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("videogame_randomized_back.Models.GameGenre", b =>
                {
                    b.HasOne("videogame_randomized_back.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("videogame_randomized_back.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("videogame_randomized_back.Models.GamePlatform", b =>
                {
                    b.HasOne("videogame_randomized_back.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("videogame_randomized_back.Models.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });
#pragma warning restore 612, 618
        }
    }
}
